# Generated by Django 4.1.5 on 2023-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TalcherDirect',
            fields=[
                ('name', models.TextField(db_column='Name', primary_key=True, serialize=False)),
                ('activity', models.TextField(blank=True, db_column='Activity', null=True)),
                ('system', models.TextField(blank=True, db_column='System', null=True)),
                ('mu', models.TextField(blank=True, db_column='MU', null=True)),
            ],
            options={
                'db_table': 'talcher direct',
                'managed': False,
            },
        ),
    ]
